// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_app/models/index.dart' as _i2;
import 'package:flutter_app/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJwtResponse_0 extends _i1.SmartFake implements _i2.JwtResponse {
  _FakeJwtResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageResponse_1 extends _i1.SmartFake
    implements _i2.MessageResponse {
  _FakeMessageResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePatient_2 extends _i1.SmartFake implements _i2.Patient {
  _FakePatient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMedicalService_3 extends _i1.SmartFake
    implements _i2.MedicalService {
  _FakeMedicalService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSejour_4 extends _i1.SmartFake implements _i2.Sejour {
  _FakeSejour_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActeMedical_5 extends _i1.SmartFake implements _i2.ActeMedical {
  _FakeActeMedical_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardStats_6 extends _i1.SmartFake
    implements _i2.DashboardStats {
  _FakeDashboardStats_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrediction_7 extends _i1.SmartFake implements _i2.Prediction {
  _FakePrediction_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvestment_8 extends _i1.SmartFake implements _i2.Investment {
  _FakeInvestment_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlert_9 extends _i1.SmartFake implements _i2.Alert {
  _FakeAlert_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReport_10 extends _i1.SmartFake implements _i2.Report {
  _FakeReport_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetting_11 extends _i1.SmartFake implements _i2.Setting {
  _FakeSetting_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMedecin_12 extends _i1.SmartFake implements _i2.Medecin {
  _FakeMedecin_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_13 extends _i1.SmartFake implements _i2.User {
  _FakeUser_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<_i2.JwtResponse> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.JwtResponse>.value(
              _FakeJwtResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i4.Future<_i2.JwtResponse>);

  @override
  _i4.Future<_i2.MessageResponse> signup(_i2.SignupRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [request]),
            returnValue: _i4.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_1(
                this,
                Invocation.method(#signup, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageResponse>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Patient>> getPatients() =>
      (super.noSuchMethod(
            Invocation.method(#getPatients, []),
            returnValue: _i4.Future<List<_i2.Patient>>.value(<_i2.Patient>[]),
          )
          as _i4.Future<List<_i2.Patient>>);

  @override
  _i4.Future<_i2.Patient> getPatient(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPatient, [id]),
            returnValue: _i4.Future<_i2.Patient>.value(
              _FakePatient_2(this, Invocation.method(#getPatient, [id])),
            ),
          )
          as _i4.Future<_i2.Patient>);

  @override
  _i4.Future<_i2.Patient> createPatient(_i2.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#createPatient, [patient]),
            returnValue: _i4.Future<_i2.Patient>.value(
              _FakePatient_2(
                this,
                Invocation.method(#createPatient, [patient]),
              ),
            ),
          )
          as _i4.Future<_i2.Patient>);

  @override
  _i4.Future<_i2.Patient> updatePatient(int? id, _i2.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#updatePatient, [id, patient]),
            returnValue: _i4.Future<_i2.Patient>.value(
              _FakePatient_2(
                this,
                Invocation.method(#updatePatient, [id, patient]),
              ),
            ),
          )
          as _i4.Future<_i2.Patient>);

  @override
  _i4.Future<void> deletePatient(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MedicalService>> getServices() =>
      (super.noSuchMethod(
            Invocation.method(#getServices, []),
            returnValue: _i4.Future<List<_i2.MedicalService>>.value(
              <_i2.MedicalService>[],
            ),
          )
          as _i4.Future<List<_i2.MedicalService>>);

  @override
  _i4.Future<_i2.MedicalService> getService(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getService, [id]),
            returnValue: _i4.Future<_i2.MedicalService>.value(
              _FakeMedicalService_3(this, Invocation.method(#getService, [id])),
            ),
          )
          as _i4.Future<_i2.MedicalService>);

  @override
  _i4.Future<_i2.MedicalService> createService(_i2.MedicalService? service) =>
      (super.noSuchMethod(
            Invocation.method(#createService, [service]),
            returnValue: _i4.Future<_i2.MedicalService>.value(
              _FakeMedicalService_3(
                this,
                Invocation.method(#createService, [service]),
              ),
            ),
          )
          as _i4.Future<_i2.MedicalService>);

  @override
  _i4.Future<_i2.MedicalService> updateService(
    int? id,
    _i2.MedicalService? service,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateService, [id, service]),
            returnValue: _i4.Future<_i2.MedicalService>.value(
              _FakeMedicalService_3(
                this,
                Invocation.method(#updateService, [id, service]),
              ),
            ),
          )
          as _i4.Future<_i2.MedicalService>);

  @override
  _i4.Future<void> deleteService(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteService, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Sejour>> getSejours() =>
      (super.noSuchMethod(
            Invocation.method(#getSejours, []),
            returnValue: _i4.Future<List<_i2.Sejour>>.value(<_i2.Sejour>[]),
          )
          as _i4.Future<List<_i2.Sejour>>);

  @override
  _i4.Future<List<_i2.Sejour>> getSejoursEnCours() =>
      (super.noSuchMethod(
            Invocation.method(#getSejoursEnCours, []),
            returnValue: _i4.Future<List<_i2.Sejour>>.value(<_i2.Sejour>[]),
          )
          as _i4.Future<List<_i2.Sejour>>);

  @override
  _i4.Future<int> getSejoursEnCoursCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSejoursEnCoursCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.Sejour> getSejour(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSejour, [id]),
            returnValue: _i4.Future<_i2.Sejour>.value(
              _FakeSejour_4(this, Invocation.method(#getSejour, [id])),
            ),
          )
          as _i4.Future<_i2.Sejour>);

  @override
  _i4.Future<_i2.Sejour> createSejour(_i2.Sejour? sejour) =>
      (super.noSuchMethod(
            Invocation.method(#createSejour, [sejour]),
            returnValue: _i4.Future<_i2.Sejour>.value(
              _FakeSejour_4(this, Invocation.method(#createSejour, [sejour])),
            ),
          )
          as _i4.Future<_i2.Sejour>);

  @override
  _i4.Future<_i2.Sejour> updateSejour(int? id, _i2.Sejour? sejour) =>
      (super.noSuchMethod(
            Invocation.method(#updateSejour, [id, sejour]),
            returnValue: _i4.Future<_i2.Sejour>.value(
              _FakeSejour_4(
                this,
                Invocation.method(#updateSejour, [id, sejour]),
              ),
            ),
          )
          as _i4.Future<_i2.Sejour>);

  @override
  _i4.Future<void> deleteSejour(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSejour, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ActeMedical>> getActesMedicaux() =>
      (super.noSuchMethod(
            Invocation.method(#getActesMedicaux, []),
            returnValue: _i4.Future<List<_i2.ActeMedical>>.value(
              <_i2.ActeMedical>[],
            ),
          )
          as _i4.Future<List<_i2.ActeMedical>>);

  @override
  _i4.Future<_i2.ActeMedical> getActeMedical(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getActeMedical, [id]),
            returnValue: _i4.Future<_i2.ActeMedical>.value(
              _FakeActeMedical_5(
                this,
                Invocation.method(#getActeMedical, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.ActeMedical>);

  @override
  _i4.Future<List<_i2.ActeMedical>> getActesMedicauxBySejour(int? sejourId) =>
      (super.noSuchMethod(
            Invocation.method(#getActesMedicauxBySejour, [sejourId]),
            returnValue: _i4.Future<List<_i2.ActeMedical>>.value(
              <_i2.ActeMedical>[],
            ),
          )
          as _i4.Future<List<_i2.ActeMedical>>);

  @override
  _i4.Future<_i2.ActeMedical> createActeMedical(_i2.ActeMedical? acte) =>
      (super.noSuchMethod(
            Invocation.method(#createActeMedical, [acte]),
            returnValue: _i4.Future<_i2.ActeMedical>.value(
              _FakeActeMedical_5(
                this,
                Invocation.method(#createActeMedical, [acte]),
              ),
            ),
          )
          as _i4.Future<_i2.ActeMedical>);

  @override
  _i4.Future<_i2.ActeMedical> updateActeMedical(
    int? id,
    _i2.ActeMedical? acte,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateActeMedical, [id, acte]),
            returnValue: _i4.Future<_i2.ActeMedical>.value(
              _FakeActeMedical_5(
                this,
                Invocation.method(#updateActeMedical, [id, acte]),
              ),
            ),
          )
          as _i4.Future<_i2.ActeMedical>);

  @override
  _i4.Future<void> deleteActeMedical(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActeMedical, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.DashboardStats> getDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStats, []),
            returnValue: _i4.Future<_i2.DashboardStats>.value(
              _FakeDashboardStats_6(
                this,
                Invocation.method(#getDashboardStats, []),
              ),
            ),
          )
          as _i4.Future<_i2.DashboardStats>);

  @override
  _i4.Future<List<_i2.ActesByTypeStats>> getActesByType() =>
      (super.noSuchMethod(
            Invocation.method(#getActesByType, []),
            returnValue: _i4.Future<List<_i2.ActesByTypeStats>>.value(
              <_i2.ActesByTypeStats>[],
            ),
          )
          as _i4.Future<List<_i2.ActesByTypeStats>>);

  @override
  _i4.Future<List<_i2.RevenusByMonthStats>> getRevenusByMonth() =>
      (super.noSuchMethod(
            Invocation.method(#getRevenusByMonth, []),
            returnValue: _i4.Future<List<_i2.RevenusByMonthStats>>.value(
              <_i2.RevenusByMonthStats>[],
            ),
          )
          as _i4.Future<List<_i2.RevenusByMonthStats>>);

  @override
  _i4.Future<List<_i2.SejoursByServiceStats>> getSejoursByService() =>
      (super.noSuchMethod(
            Invocation.method(#getSejoursByService, []),
            returnValue: _i4.Future<List<_i2.SejoursByServiceStats>>.value(
              <_i2.SejoursByServiceStats>[],
            ),
          )
          as _i4.Future<List<_i2.SejoursByServiceStats>>);

  @override
  _i4.Future<List<_i2.Prediction>> getPredictions() =>
      (super.noSuchMethod(
            Invocation.method(#getPredictions, []),
            returnValue: _i4.Future<List<_i2.Prediction>>.value(
              <_i2.Prediction>[],
            ),
          )
          as _i4.Future<List<_i2.Prediction>>);

  @override
  _i4.Future<_i2.Prediction> getPrediction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPrediction, [id]),
            returnValue: _i4.Future<_i2.Prediction>.value(
              _FakePrediction_7(this, Invocation.method(#getPrediction, [id])),
            ),
          )
          as _i4.Future<_i2.Prediction>);

  @override
  _i4.Future<List<_i2.Prediction>> getPredictionsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getPredictionsByType, [type]),
            returnValue: _i4.Future<List<_i2.Prediction>>.value(
              <_i2.Prediction>[],
            ),
          )
          as _i4.Future<List<_i2.Prediction>>);

  @override
  _i4.Future<_i2.Prediction> generatePrediction(
    String? type,
    String? titre,
    String? periodePrevue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generatePrediction, [
              type,
              titre,
              periodePrevue,
            ]),
            returnValue: _i4.Future<_i2.Prediction>.value(
              _FakePrediction_7(
                this,
                Invocation.method(#generatePrediction, [
                  type,
                  titre,
                  periodePrevue,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Prediction>);

  @override
  _i4.Future<_i2.Prediction> createPrediction(_i2.Prediction? prediction) =>
      (super.noSuchMethod(
            Invocation.method(#createPrediction, [prediction]),
            returnValue: _i4.Future<_i2.Prediction>.value(
              _FakePrediction_7(
                this,
                Invocation.method(#createPrediction, [prediction]),
              ),
            ),
          )
          as _i4.Future<_i2.Prediction>);

  @override
  _i4.Future<_i2.Prediction> updatePrediction(
    int? id,
    _i2.Prediction? prediction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrediction, [id, prediction]),
            returnValue: _i4.Future<_i2.Prediction>.value(
              _FakePrediction_7(
                this,
                Invocation.method(#updatePrediction, [id, prediction]),
              ),
            ),
          )
          as _i4.Future<_i2.Prediction>);

  @override
  _i4.Future<void> deletePrediction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePrediction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Investment>> getInvestments() =>
      (super.noSuchMethod(
            Invocation.method(#getInvestments, []),
            returnValue: _i4.Future<List<_i2.Investment>>.value(
              <_i2.Investment>[],
            ),
          )
          as _i4.Future<List<_i2.Investment>>);

  @override
  _i4.Future<_i2.Investment> getInvestment(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestment, [id]),
            returnValue: _i4.Future<_i2.Investment>.value(
              _FakeInvestment_8(this, Invocation.method(#getInvestment, [id])),
            ),
          )
          as _i4.Future<_i2.Investment>);

  @override
  _i4.Future<Map<String, dynamic>> getInvestmentStats() =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Investment> createInvestment(_i2.Investment? investment) =>
      (super.noSuchMethod(
            Invocation.method(#createInvestment, [investment]),
            returnValue: _i4.Future<_i2.Investment>.value(
              _FakeInvestment_8(
                this,
                Invocation.method(#createInvestment, [investment]),
              ),
            ),
          )
          as _i4.Future<_i2.Investment>);

  @override
  _i4.Future<_i2.Investment> updateInvestment(
    int? id,
    _i2.Investment? investment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInvestment, [id, investment]),
            returnValue: _i4.Future<_i2.Investment>.value(
              _FakeInvestment_8(
                this,
                Invocation.method(#updateInvestment, [id, investment]),
              ),
            ),
          )
          as _i4.Future<_i2.Investment>);

  @override
  _i4.Future<void> deleteInvestment(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInvestment, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Alert>> getAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getAlerts, []),
            returnValue: _i4.Future<List<_i2.Alert>>.value(<_i2.Alert>[]),
          )
          as _i4.Future<List<_i2.Alert>>);

  @override
  _i4.Future<_i2.Alert> getAlert(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAlert, [id]),
            returnValue: _i4.Future<_i2.Alert>.value(
              _FakeAlert_9(this, Invocation.method(#getAlert, [id])),
            ),
          )
          as _i4.Future<_i2.Alert>);

  @override
  _i4.Future<List<_i2.Alert>> getUnreadAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadAlerts, []),
            returnValue: _i4.Future<List<_i2.Alert>>.value(<_i2.Alert>[]),
          )
          as _i4.Future<List<_i2.Alert>>);

  @override
  _i4.Future<List<_i2.Alert>> getUnresolvedAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#getUnresolvedAlerts, []),
            returnValue: _i4.Future<List<_i2.Alert>>.value(<_i2.Alert>[]),
          )
          as _i4.Future<List<_i2.Alert>>);

  @override
  _i4.Future<Map<String, dynamic>> getAlertStats() =>
      (super.noSuchMethod(
            Invocation.method(#getAlertStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Alert> markAlertAsRead(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAlertAsRead, [id]),
            returnValue: _i4.Future<_i2.Alert>.value(
              _FakeAlert_9(this, Invocation.method(#markAlertAsRead, [id])),
            ),
          )
          as _i4.Future<_i2.Alert>);

  @override
  _i4.Future<_i2.Alert> markAlertAsResolved(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAlertAsResolved, [id]),
            returnValue: _i4.Future<_i2.Alert>.value(
              _FakeAlert_9(this, Invocation.method(#markAlertAsResolved, [id])),
            ),
          )
          as _i4.Future<_i2.Alert>);

  @override
  _i4.Future<_i2.Alert> createAlert(_i2.Alert? alert) =>
      (super.noSuchMethod(
            Invocation.method(#createAlert, [alert]),
            returnValue: _i4.Future<_i2.Alert>.value(
              _FakeAlert_9(this, Invocation.method(#createAlert, [alert])),
            ),
          )
          as _i4.Future<_i2.Alert>);

  @override
  _i4.Future<_i2.Alert> updateAlert(int? id, _i2.Alert? alert) =>
      (super.noSuchMethod(
            Invocation.method(#updateAlert, [id, alert]),
            returnValue: _i4.Future<_i2.Alert>.value(
              _FakeAlert_9(this, Invocation.method(#updateAlert, [id, alert])),
            ),
          )
          as _i4.Future<_i2.Alert>);

  @override
  _i4.Future<void> deleteAlert(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlert, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Report>> getReports() =>
      (super.noSuchMethod(
            Invocation.method(#getReports, []),
            returnValue: _i4.Future<List<_i2.Report>>.value(<_i2.Report>[]),
          )
          as _i4.Future<List<_i2.Report>>);

  @override
  _i4.Future<_i2.Report> getReport(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReport, [id]),
            returnValue: _i4.Future<_i2.Report>.value(
              _FakeReport_10(this, Invocation.method(#getReport, [id])),
            ),
          )
          as _i4.Future<_i2.Report>);

  @override
  _i4.Future<List<_i2.Report>> getReportsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getReportsByType, [type]),
            returnValue: _i4.Future<List<_i2.Report>>.value(<_i2.Report>[]),
          )
          as _i4.Future<List<_i2.Report>>);

  @override
  _i4.Future<List<_i2.Report>> getReportsByPeriode(String? periode) =>
      (super.noSuchMethod(
            Invocation.method(#getReportsByPeriode, [periode]),
            returnValue: _i4.Future<List<_i2.Report>>.value(<_i2.Report>[]),
          )
          as _i4.Future<List<_i2.Report>>);

  @override
  _i4.Future<_i2.Report> createReport(_i2.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#createReport, [report]),
            returnValue: _i4.Future<_i2.Report>.value(
              _FakeReport_10(this, Invocation.method(#createReport, [report])),
            ),
          )
          as _i4.Future<_i2.Report>);

  @override
  _i4.Future<_i2.Report> updateReport(int? id, _i2.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#updateReport, [id, report]),
            returnValue: _i4.Future<_i2.Report>.value(
              _FakeReport_10(
                this,
                Invocation.method(#updateReport, [id, report]),
              ),
            ),
          )
          as _i4.Future<_i2.Report>);

  @override
  _i4.Future<void> deleteReport(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReport, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Setting>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i4.Future<List<_i2.Setting>>.value(<_i2.Setting>[]),
          )
          as _i4.Future<List<_i2.Setting>>);

  @override
  _i4.Future<_i2.Setting> getSetting(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [id]),
            returnValue: _i4.Future<_i2.Setting>.value(
              _FakeSetting_11(this, Invocation.method(#getSetting, [id])),
            ),
          )
          as _i4.Future<_i2.Setting>);

  @override
  _i4.Future<_i2.Setting> getSettingByCle(String? cle) =>
      (super.noSuchMethod(
            Invocation.method(#getSettingByCle, [cle]),
            returnValue: _i4.Future<_i2.Setting>.value(
              _FakeSetting_11(this, Invocation.method(#getSettingByCle, [cle])),
            ),
          )
          as _i4.Future<_i2.Setting>);

  @override
  _i4.Future<List<_i2.Setting>> getSettingsByCategorie(String? categorie) =>
      (super.noSuchMethod(
            Invocation.method(#getSettingsByCategorie, [categorie]),
            returnValue: _i4.Future<List<_i2.Setting>>.value(<_i2.Setting>[]),
          )
          as _i4.Future<List<_i2.Setting>>);

  @override
  _i4.Future<_i2.Setting> createSetting(_i2.Setting? setting) =>
      (super.noSuchMethod(
            Invocation.method(#createSetting, [setting]),
            returnValue: _i4.Future<_i2.Setting>.value(
              _FakeSetting_11(
                this,
                Invocation.method(#createSetting, [setting]),
              ),
            ),
          )
          as _i4.Future<_i2.Setting>);

  @override
  _i4.Future<_i2.Setting> updateSetting(int? id, _i2.Setting? setting) =>
      (super.noSuchMethod(
            Invocation.method(#updateSetting, [id, setting]),
            returnValue: _i4.Future<_i2.Setting>.value(
              _FakeSetting_11(
                this,
                Invocation.method(#updateSetting, [id, setting]),
              ),
            ),
          )
          as _i4.Future<_i2.Setting>);

  @override
  _i4.Future<void> deleteSetting(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSetting, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> askAI(String? question) =>
      (super.noSuchMethod(
            Invocation.method(#askAI, [question]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.Medecin>> getMedecins() =>
      (super.noSuchMethod(
            Invocation.method(#getMedecins, []),
            returnValue: _i4.Future<List<_i2.Medecin>>.value(<_i2.Medecin>[]),
          )
          as _i4.Future<List<_i2.Medecin>>);

  @override
  _i4.Future<_i2.Medecin> getMedecin(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMedecin, [id]),
            returnValue: _i4.Future<_i2.Medecin>.value(
              _FakeMedecin_12(this, Invocation.method(#getMedecin, [id])),
            ),
          )
          as _i4.Future<_i2.Medecin>);

  @override
  _i4.Future<List<_i2.Medecin>> getMedecinsByService(int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getMedecinsByService, [serviceId]),
            returnValue: _i4.Future<List<_i2.Medecin>>.value(<_i2.Medecin>[]),
          )
          as _i4.Future<List<_i2.Medecin>>);

  @override
  _i4.Future<_i2.Medecin> createMedecin(_i2.Medecin? medecin) =>
      (super.noSuchMethod(
            Invocation.method(#createMedecin, [medecin]),
            returnValue: _i4.Future<_i2.Medecin>.value(
              _FakeMedecin_12(
                this,
                Invocation.method(#createMedecin, [medecin]),
              ),
            ),
          )
          as _i4.Future<_i2.Medecin>);

  @override
  _i4.Future<_i2.Medecin> updateMedecin(int? id, _i2.Medecin? medecin) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedecin, [id, medecin]),
            returnValue: _i4.Future<_i2.Medecin>.value(
              _FakeMedecin_12(
                this,
                Invocation.method(#updateMedecin, [id, medecin]),
              ),
            ),
          )
          as _i4.Future<_i2.Medecin>);

  @override
  _i4.Future<void> deleteMedecin(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedecin, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.User>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i4.Future<List<_i2.User>>.value(<_i2.User>[]),
          )
          as _i4.Future<List<_i2.User>>);

  @override
  _i4.Future<_i2.User> getUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i4.Future<_i2.User>.value(
              _FakeUser_13(this, Invocation.method(#getUser, [id])),
            ),
          )
          as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userData]),
            returnValue: _i4.Future<_i2.User>.value(
              _FakeUser_13(this, Invocation.method(#createUser, [userData])),
            ),
          )
          as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> updateUser(int? id, Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [id, userData]),
            returnValue: _i4.Future<_i2.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateUser, [id, userData]),
              ),
            ),
          )
          as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Role>> getRoles() =>
      (super.noSuchMethod(
            Invocation.method(#getRoles, []),
            returnValue: _i4.Future<List<_i2.Role>>.value(<_i2.Role>[]),
          )
          as _i4.Future<List<_i2.Role>>);
}
